trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  azureSubscription: 'Coastal and Freshwater Dev'
  tag: '$(Build.BuildId)'

stages:
# - stage: 'Build'
#   displayName: 'Build and push'
#   jobs:  
#   - job: 'Build'
#     displayName: 'Build job'
#     pool:
#       vmImage: 'ubuntu-18.04'
#     steps:
#     - task: Docker@2
#       displayName: 'Build and push the image to container registry'
#       inputs:
#         command: buildAndPush
#         buildContext: $(Build.Repository.LocalPath)
#         repository: $(webRepository)
#         dockerfile: '$(Build.SourcesDirectory)/tileLayer/Dockerfile'
#         containerRegistry: 'Container Registry Connection'
#         tags: |
#           $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  #dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppName)
       azureSubscription: $(azureSubscription)
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)